### ISSUE TITLE
Let's Prevent Bot Fights

### ISSUE THREAD

**Issue by ProbablePrime** [PolyExtend/StreamLink#1]
My bots are fighting your bots.

Can we agree a format for ignoring each others bots somehow?

My code ignores "BeamLink" "BeamLinkDev" and now i need to ignore "StreamLink"

gotta be a better way to do that.

I can't ignore *link* because it'll offend legend of zelda fans.

How about !ignore <username> or something along those lines which will ignore a user on both sides of the link.

If you want I can PR this to BeamLink 1.0 but i have no idea what's going on. Is the "StreamLink" user running this repo or beamlink1.0. 

Let me know if i can help you.

**Comment by Tromino** [comment]
I don't think I really understand what you're saying. :P

**Comment by ProbablePrime** [comment]
I was running a copy of https://github.com/ProbablePrime/MultiLink in someones channel because of beamlink being missing in action.

Suddenly StreamLink randomly appears in beam but not twitch and starts infinite looping with my linker. 

The caster !unlinks streamlink.


Several minutes later StreamLink appears in twitch and relays a ton of old messages which my bot then sends back to beam. Which your bot then sent back to Twitch and it just looped. 

I was trying to figure out if there was a smart way to avoid scenarios like this. I guess the best way is to just leave it up to the caster though. 

Do you understand now?

**Comment by Tromino** [comment]
StreamLink_ and StreamLinkDev_ should be the final usernames for now on both Beam and Twitch. If I ever change it again I'll notify you.

**Comment by ProbablePrime** [comment]
Sure that works!

Thanks!
